import type { CourseDesign } from "~/lib/course-design";
import { designMinutes } from "~/lib/course-design";
import { FORMAT_LABELS } from "~/lib/proposal-request";

export function CourseEditor({ design, onChange }: { design: CourseDesign; onChange: (value: CourseDesign) => void }) {
  const change = <K extends keyof CourseDesign>(key: K, value: CourseDesign[K]) => onChange({ ...design, [key]: value });
  const field = (key: keyof CourseDesign, label: string, multiline = false, hint = "") => <div className="course-field"><label htmlFor={`design-${key}`}>{label}</label>{hint && <small>{hint}</small>}{multiline ? <textarea id={`design-${key}`} rows={3} maxLength={6000} value={design[key] as string} onChange={e => change(key, e.target.value as never)} /> : <input id={`design-${key}`} maxLength={6000} value={design[key] as string} onChange={e => change(key, e.target.value as never)} />}</div>;
  const updateModule = (index: number, patch: Partial<CourseDesign["modules"][number]>) => change("modules", design.modules.map((module, i) => i === index ? { ...module, ...patch } : module));
  const updateObjective = (index: number, patch: Partial<CourseDesign["objectives"][number]>) => change("objectives", design.objectives.map((objective, i) => i === index ? { ...objective, ...patch } : objective));
  return <div className="course-editor">
    <section className="course-panel"><h2>1. เข้าใจองค์กรและผู้เรียน</h2>{field("title", "ชื่อหลักสูตร")}{field("organization", "องค์กร / บริษัท")}{field("challenge", "โจทย์และสถานการณ์ที่ต้องการพัฒนา", true, "ระบุสิ่งที่เกิดขึ้นจริงและผลกระทบต่อการทำงาน")}{field("businessGoal", "ผลลัพธ์ที่อยากเห็นในงานจริง", true)}{field("audience", "กลุ่มผู้เรียนและความพร้อม", true)}
      <div className="course-columns"><div className="course-field"><label htmlFor="design-participants">จำนวนผู้เรียน (คน)</label><input id="design-participants" type="number" min={0} max={10000} value={design.participants} onChange={e => change("participants", Number(e.target.value))} /></div><div className="course-field"><label htmlFor="design-format">รูปแบบการเรียนรู้</label><select id="design-format" value={design.format} onChange={e => change("format", e.target.value)}>{Object.entries(FORMAT_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div></div><div className="course-columns">{field("timeline", "ช่วงเวลาที่ต้องการจัด")}{field("location", "สถานที่ / ช่องทางออนไลน์")}</div>
      {field("budgetExpectation", "กรอบงบประมาณที่องค์กรแจ้ง", false, "ข้อมูลเพื่อออกแบบขอบเขต ยังไม่ใช่ราคาที่เสนอ")}{field("constraints", "ข้อจำกัดและสิ่งที่ต้องคำนึงถึง", true)}
    </section>
    <section className="course-panel"><h2>2. วัตถุประสงค์ที่สังเกตได้</h2><p>เขียนว่าผู้เรียนจะทำอะไรได้ และใช้หลักฐานใดยืนยัน</p>
      {design.objectives.map((objective, index) => <div className="course-item" key={objective.id}><div className="course-item-head"><h3>วัตถุประสงค์ {index + 1}</h3><button type="button" className="course-link danger" onClick={() => { onChange({ ...design, objectives: design.objectives.filter(o => o.id !== objective.id), modules: design.modules.map(m => ({ ...m, objectiveIds: m.objectiveIds.filter(id => id !== objective.id) })) }); }}>ลบวัตถุประสงค์ {index + 1}</button></div><label htmlFor={`objective-${objective.id}`}>พฤติกรรม / ทักษะที่ต้องการ</label><textarea id={`objective-${objective.id}`} maxLength={6000} rows={2} value={objective.behavior} onChange={e => updateObjective(index, { behavior: e.target.value })} /><label htmlFor={`evidence-${objective.id}`}>หลักฐานและเกณฑ์ที่ใช้ประเมิน</label><textarea id={`evidence-${objective.id}`} maxLength={6000} rows={2} placeholder="เช่น ฝึก Feedback แล้วระบุสถานการณ์ พฤติกรรม และข้อตกลงได้ครบ" value={objective.evidence} onChange={e => updateObjective(index, { evidence: e.target.value })} /></div>)}
      <button className="course-button secondary" disabled={design.objectives.length >= 30} onClick={() => change("objectives", [...design.objectives, { id: crypto.randomUUID(), behavior: "", evidence: "" }])}>เพิ่มวัตถุประสงค์</button>
    </section>
    <section className="course-panel"><h2>3. ออกแบบกิจกรรมและเวลา</h2><div className="course-field"><label htmlFor="design-availableMinutes">กรอบเวลากิจกรรมทั้งหมด (นาที ไม่รวมพัก)</label><input id="design-availableMinutes" type="number" min={0} max={100000} value={design.availableMinutes} onChange={e => change("availableMinutes", Number(e.target.value))} /><p className={designMinutes(design) > design.availableMinutes ? "course-warning" : ""}>ใช้เวลา {designMinutes(design)} / {design.availableMinutes} นาที</p></div>
      {design.modules.map((module, index) => <div className="course-item" key={module.id}><div className="course-item-head"><h3>กิจกรรม {index + 1}</h3><div className="course-actions"><button aria-label={`เลื่อนกิจกรรม ${index + 1} ขึ้น`} disabled={index === 0} onClick={() => { const modules = [...design.modules]; [modules[index - 1], modules[index]] = [modules[index], modules[index - 1]]; change("modules", modules); }}>↑</button><button aria-label={`เลื่อนกิจกรรม ${index + 1} ลง`} disabled={index === design.modules.length - 1} onClick={() => { const modules = [...design.modules]; [modules[index + 1], modules[index]] = [modules[index], modules[index + 1]]; change("modules", modules); }}>↓</button><button className="course-link danger" onClick={() => change("modules", design.modules.filter(m => m.id !== module.id))}>ลบกิจกรรม {index + 1}</button></div></div>
        <div className="course-columns"><div><label htmlFor={`module-${module.id}`}>ชื่อกิจกรรม</label><input id={`module-${module.id}`} maxLength={6000} value={module.title} onChange={e => updateModule(index, { title: e.target.value })} /></div><div><label htmlFor={`minutes-${module.id}`}>เวลา (นาที)</label><input id={`minutes-${module.id}`} type="number" min={0} max={10000} value={module.minutes} onChange={e => updateModule(index, { minutes: Number(e.target.value) })} /></div></div>
        <label htmlFor={`activity-${module.id}`}>กระบวนการ / วิธีดำเนินกิจกรรม</label><textarea id={`activity-${module.id}`} maxLength={6000} rows={3} value={module.activity} onChange={e => updateModule(index, { activity: e.target.value })} /><label htmlFor={`output-${module.id}`}>ผลงานหรือพฤติกรรมที่ต้องได้จากกิจกรรม</label><textarea id={`output-${module.id}`} maxLength={6000} rows={2} value={module.output} onChange={e => updateModule(index, { output: e.target.value })} />
        <fieldset><legend>รองรับวัตถุประสงค์ใด?</legend>{design.objectives.map((o, i) => <label className="course-checkbox" key={o.id}><input type="checkbox" checked={module.objectiveIds.includes(o.id)} onChange={e => updateModule(index, { objectiveIds: e.target.checked ? [...module.objectiveIds, o.id] : module.objectiveIds.filter(id => id !== o.id) })} /><span>{i + 1}. {o.behavior || "ยังไม่ได้เขียนวัตถุประสงค์"}</span></label>)}</fieldset>
      </div>)}<button className="course-button secondary" disabled={design.modules.length >= 50} onClick={() => change("modules", [...design.modules, { id: crypto.randomUUID(), title: "", minutes: 60, objectiveIds: [], activity: "", output: "" }])}>เพิ่มกิจกรรม</button>
    </section>
    <section className="course-panel"><h2>4. ประเมินและนำไปใช้ในงานจริง</h2>{([ ["baseline", "ก่อนเรียน: ข้อมูลตั้งต้นและวิธีเก็บ"], ["after", "หลังเรียน: ทักษะ / ผลงานที่ต้องประเมิน"], ["followUp", "หลังกลับไปทำงาน: แผนทดลองและจุดติดตาม"], ["owner", "ผู้รับผิดชอบและผู้สนับสนุนการติดตาม"] ] as const).map(([key, label]) => <div className="course-field" key={key}><label htmlFor={`evaluation-${key}`}>{label}</label><textarea id={`evaluation-${key}`} rows={3} maxLength={6000} value={design.evaluation[key]} onChange={e => change("evaluation", { ...design.evaluation, [key]: e.target.value })} /></div>)}</section>
    <section className="course-panel"><h2>5. ขอบเขตสำหรับเสนอองค์กร</h2>{field("deliverables", "สิ่งส่งมอบและรูปแบบเอกสาร", true)}{field("organizationSupport", "สิ่งที่องค์กรต้องสนับสนุน", true, "เช่น ผู้ประสานงาน สถานที่ เคสฝึก และหัวหน้าที่ติดตามผล")}{field("scope", "ขอบเขต สิ่งที่รวม / ไม่รวม และเงื่อนไข", true)}{field("investment", "งบประมาณและเงื่อนไขพิจารณาราคา", true, "ระบุราคาที่ทีมตรวจแล้ว หรือรายการที่ต้องประเมินก่อนเสนอราคา")}{field("notes", "หมายเหตุสำหรับข้อเสนอ", true)}</section>
  </div>;
}
