import { Link, useParams } from "react-router";
import type { Route } from "./+types/program";
import type { CSSProperties } from "react";
import { ProgramLayout } from "~/components/layout/ProgramLayout";
import { GROWTH_PROGRAMS, getProgram, programUrl, requestUrl } from "~/lib/programs";

export function meta({ params }: Route.MetaArgs) {
  const program = getProgram(params.slug);
  const title = program ? `${program.title} · ${program.code} | CHOOMCHAM HOUSE` : "ไม่พบหลักสูตร | CHOOMCHAM HOUSE";
  return [{ title }, { name: "description", content: program?.description || "เลือกหลักสูตรสำหรับองค์กร" }, { property: "og:title", content: title }, { property: "og:description", content: program?.description || "" }, { property: "og:type", content: "website" }, { property: "og:image", content: "https://choomcham.pages.dev/chumcham.png" }, { tagName: "link", rel: "canonical", href: `https://choomcham.pages.dev/programs/${params.slug}` }, ...(!program ? [{ name: "robots", content: "noindex" }] : [])];
}
export default function ProgramPage() {
  const { slug } = useParams(); const program = getProgram(slug);
  if (!program) return <ProgramLayout><section className="program-container program-intro"><h1>ไม่พบหลักสูตรนี้</h1><Link className="program-button" to="/programs">เลือกดูทุกโปรแกรม</Link></section></ProgramLayout>;
  const flagship = program.level === "FLAGSHIP";
  return <ProgramLayout><div style={{ "--program-accent": program.accent } as CSSProperties}>
    <section className="program-hero program-container"><div><Link className="program-text-link" to="/programs">← ทุกโปรแกรม</Link><span className="program-eyebrow">{program.level} · {program.code}</span><h1>{program.title}</h1><p className="program-lead">{program.hook}</p><p>{program.description}</p><div className="program-actions"><Link className="program-button" to={requestUrl(program.slug)}>ขอ Proposal หลักสูตรนี้ →</Link><a className="program-button secondary" href="#learning-design">ดูโครงสร้างการเรียนรู้</a></div></div><aside className="program-hero-note"><span className="program-eyebrow">{flagship ? "FROM ZOMBIE → ALIVE" : "GROW FROM WITHIN"}</span><div className="program-growth-art" aria-hidden="true"><span>{flagship ? "✨" : program.level.replace("LEVEL ", "0")}</span></div><h2>ตัวจริงต้องมีที่ยืน</h2><p>{program.audience}</p><small>รูปแบบตั้งต้น: {program.duration}</small></aside></section>
    <section className="program-band"><div className="program-container"><span className="program-eyebrow">START WITH YOUR REAL CHALLENGE</span><h2>โจทย์เหล่านี้คุ้นกับองค์กรคุณไหม?</h2><div className="program-three">{program.pains.map((item, i) => <article className="program-card" key={item}><span className="program-number">0{i + 1}</span><h3>{item}</h3></article>)}</div></div></section>
    <section className="program-container program-section"><span className="program-eyebrow">LEARNING OUTCOMES</span><h2>จากการเรียนรู้ สู่พฤติกรรมที่ลงมือทำ</h2><p>เป้าหมายการเรียนรู้เบื้องต้น ซึ่งจะปรับให้ตรงกับสถานการณ์และระดับผู้เรียนขององค์กร</p><ol className="program-outcomes">{program.objectives.map(item => <li key={item}>{item}</li>)}</ol></section>
    <section id="learning-design" className="program-band"><div className="program-container"><span className="program-eyebrow">EXPERIENCE → REFLECTION → ACTION</span><h2>{flagship ? "4 โมดูล เชื่อมการเติบโตทั้ง 5 ระดับ" : "โครงสร้างการเรียนรู้"}</h2><p>ฝึกจากประสบการณ์ สะท้อนสิ่งที่ค้นพบ และออกแบบการนำไปใช้ในงานจริง</p><div className="program-module-list">{program.modules.map((module, i) => <article className="program-module" key={module.title}><span className="program-number">0{i + 1}</span><div><h3>{module.title}</h3><p>{module.activity}</p><div className="program-output"><strong>สิ่งที่ได้ลงมือสร้าง</strong><p>{module.output}</p></div></div></article>)}</div><p className="program-note">ลำดับกิจกรรมและระยะเวลาเป็นกรอบตั้งต้นสำหรับออกแบบร่วมกัน ยังไม่ใช่ตารางอบรมที่ยืนยันแล้ว</p></div></section>
    <section className="program-container program-section program-two"><div><span className="program-eyebrow">TAKE IT BACK TO WORK</span><h2>สิ่งส่งมอบที่นำกลับไปใช้</h2><ul>{program.deliverables.map(item => <li key={item}>{item}</li>)}</ul></div><div><span className="program-eyebrow">MAKE GROWTH VISIBLE</span><h2>วางแผนวัดผลร่วมกัน</h2><ul>{program.measures.map(item => <li key={item}>{item}</li>)}</ul><p className="program-note">ตกลงตัวชี้วัดและช่วงติดตามก่อนเริ่ม โดยไม่ใช้คะแนนความพึงพอใจแทนหลักฐานการเปลี่ยนพฤติกรรม</p></div></section>
    <section className="program-container program-section"><div className="program-proposal-callout"><div><span className="program-eyebrow">TAILORED FOR YOUR ORGANIZATION</span><h2>เริ่มจากโจทย์ของคุณ<br />แล้วออกแบบเส้นทางไปด้วยกัน</h2><p>ส่งข้อมูลบริบท กลุ่มผู้เรียน และผลลัพธ์ที่อยากเห็น ทีมงานจะใช้เป็นฐานหารือเพื่อจัดทำ Proposal พร้อมขอบเขตและงบประมาณ</p></div><div className="program-actions"><Link className="program-button" to={requestUrl(program.slug)}>ขอ Proposal หลักสูตรนี้</Link><Link className="program-button secondary" to={`/proposal?programSlug=${program.slug}`}>ดูกรอบหลักสูตร / พิมพ์ PDF</Link></div></div></section>
    <section className="program-container program-section"><h2>คำถามก่อนเริ่ม</h2><details><summary>ต้องเรียนตามลำดับทั้ง 5 ระดับไหม?</summary><p>เลือกจุดเริ่มต้นตามโจทย์และความพร้อมได้ หากต้องการพัฒนาต่อเนื่อง ทีมงานจะช่วยเชื่อมระดับที่เกี่ยวข้องเป็นเส้นทางเดียวกัน</p></details><details><summary>ระยะเวลาและค่าใช้จ่ายเท่าไร?</summary><p>{program.duration} เป็นรูปแบบตั้งต้น ค่าใช้จ่ายขึ้นกับจำนวนผู้เรียน การปรับเนื้อหา ทีมวิทยากร สถานที่ และการติดตามผล โดยยืนยันในข้อเสนอเฉพาะองค์กร</p></details><details><summary>หลังส่งคำขอจะได้อะไร?</summary><p>ทีมงานรับข้อมูลเพื่อพูดคุยยืนยันโจทย์ ก่อนจัดทำข้อเสนอ การส่งคำขอยังไม่ใช่การจองหรือยืนยันค่าใช้จ่าย</p></details></section>
    <nav className="program-container program-related" aria-label="ระดับอื่นที่เกี่ยวข้อง">{GROWTH_PROGRAMS.filter(p => p.slug !== program.slug).map(p => <Link key={p.slug} to={programUrl(p.slug)}>{p.level} · {p.level === "FLAGSHIP" ? "หลักสูตรเรือธง" : p.code} →</Link>)}</nav>
  </div></ProgramLayout>;
}
